baseurl = "/"
title = "Stats and R"
author = "Antoine Soetewey"
canonifyurls = true
languagecode = "en-US"
paginate = 3
theme = "hugo-renga"

enableEmoji = true
hasCJKLanguage = true

# googleAnalytics = "UA-00000000-1"
# disqusShortname = "your-disqus-shortname"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
post = "/:year/:month/:day/:slug/"

[params]
pagetitle = "Stats and R"
copyright = "© 2019 Antoine Soetewey"
copyrightUrl = "https://statsandr.netlify.com"
description = "A blog about statistics and R."
faviconfile = "image/favicon.png"
logofile = "image/avatar.png"
posts_navigation = true
uselatex = true
highlightjs = true
progressively = false

github = "AntoineSoetewey"
# twitter = "nanxstats"
linkedin = "antoinesoetewey"
email = "ant.soetewey@gmail.com"

[[menu.primary]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.primary]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 2

[[menu.primary]]
identifier = "perso"
name = "Personal Website"
url = "https://www.antoinesoetewey.com/"
weight = 3
