baseurl = "https://www.statsandr.com/"
title = "Stats and R"
author = "Antoine Soetewey"
canonifyurls = true
languagecode = "en-US"
paginate = 3
theme = "hugo-renga"

enableEmoji = true
# hasCJKLanguage = true

googleAnalytics = "UA-86997981-2"
disqusShortname = "statsandr"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# [permalinks]
# post = "/:year/:month/:day/:slug/"

[params]
pagetitle = "Stats and R"
author = "Antoine Soetewey"
copyright = "© 2019 Antoine Soetewey."
copyrightUrl = "/"
description = "A blog about statistics and its applications in R."
faviconfile = "image/favicon.png"
logofile = "image/avatar.png"
posts_navigation = true
uselatex = true
highlightjs = true
progressively = false

github = "AntoineSoetewey"
# twitter = ""
linkedin = "antoinesoetewey"
# email = ""

[[menu.primary]]
identifier = "Posts"
name = "Posts"
url = "/blog/"
weight = 1

[[menu.primary]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 2

[[menu.primary]]
identifier = "about"
name = "About"
url = "/about/"
weight = 3

[[menu.primary]]
identifier = "subscribe"
name = "Subscribe"
url = "/subscribe/"
weight = 4

[[menu.primary]]
identifier = "links"
name = "Links"
url = "/links/"
weight = 5

[[menu.primary]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 6