baseurl = "/"
title = "Stats and R"
author = "Antoine Soetewey"
canonifyurls = true
languagecode = "en-US"
paginate = 3
theme = "hugo-renga"

enableEmoji = true
# hasCJKLanguage = true

# googleAnalytics = "UA-00000000-1"
# disqusShortname = "your-disqus-shortname"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

# [permalinks]
# post = "/:year/:month/:day/:slug/"

[params]
pagetitle = "Stats and R"
author = "Antoine Soetewey"
copyright = "© 2019 Antoine Soetewey."
copyrightUrl = "/"
description = "A blog about statistics and R."
faviconfile = "image/favicon.png"
logofile = "image/avatar.png"
posts_navigation = true
uselatex = true
highlightjs = true
progressively = false

github = "AntoineSoetewey"
# twitter = "nanxstats"
linkedin = "antoinesoetewey"
email = "ant.soetewey@gmail.com"

[[menu.primary]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 1

[[menu.main]]
identifier = "categories"
name = "Categories"
url = "/categories/"
weight = 2

[[menu.primary]]
identifier = "about"
name = "About"
url = "/about/"
weight = 3

[[menu.primary]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 4
