---
title: A guide on how to read statistical tables
author: Antoine Soetewey
date: '2020-01-06'
slug: a-guide-on-how-to-read-statistical-tables
categories: []
tags:
  - Statistics
  - Shiny
meta_img: image/image.png
# description: Description for the page.
output:
  blogdown::html_page:
    toc: true
# draft: true
---

Below a Shiny app to help you read the main statistical tables:

* [Statistics-101](https://antoinesoetewey.shinyapps.io/statistics-101/)

This Shiny app helps you to compute probabilities for the main probability distributions. How to use this app?

1. Choose the distribution
1. Set the paremeter(s) of the distribution
1. Select whether you want to find the lower tail, upper tail or an interval
1. Choose x

On the right panel (or below depending on the size of your screen) you will see:

* a recap of the data you just entered
* the numerical solution (i.e., the probability),
* a visualization of the solution
* the probability density function together with the mean, standard deviation and variance

I hope you will find this app useful. As always, if you find a mistake/bug or if you have any questions do not hesitate to let me know in the comment section below, <a href="https://github.com/AntoineSoetewey/statsandr/issues" target="_blank" rel="noopener">raise an issue on GitHub</a> or [contact me](/contact/). Get updates everytime a new article is published by [subscribing to this blog](/subscribe/).
