---
title: A Shiny app for inferential statistics
author: Antoine Soetewey
date: '2020-01-15'
slug: a-shiny-app-for-inferential-statistics
categories: []
tags:
  - Shiny
  - Statistics
meta_img: image/image.png
# description: Description for the page.
output:
  blogdown::html_page:
    toc: false
# draft: true
---

Statistics is divided into two main branches:

* Descriptive statistics
* Inferential statistics

Descriptive statistics provide a summary of the data; it helps explaining the data in a concise way without losing too much information. Data can be summarized numerically or graphically.
<!-- See [descriptive statistics by hand](/blog/descriptive-statistics-by-hand/) or [in R](/blog/descriptive-statistics-in-r/) to learn more about this branch of statistics. -->

Inferential statistics use a random sample of data taken from a population to make inferences (i.e., to deduct) about the population. In other words, information from the sample is used to make generalizations about the parameter of interest in the population. The two major tools in inferential statistics are confidence intervals and hypothesis tests. Here is a Shiny app which helps you to use these two tools:

* [Statistics-201](https://antoinesoetewey.shinyapps.io/statistics-201/)

This Shiny app focuses on confidence intervals and hypothesis tests for:

* 1 and 2 means (with unpaired and paired samples)
* 1 and 2 proportions
* 1 and 2 variances

# How to use this app?

Follow these steps:

1. Open the app via this [link](https://antoinesoetewey.shinyapps.io/statistics-201/)
1. Choose the statistic you want to do inference for (i.e., mean(s), proportion(s) or variance(s))
1. Write your data in Sample. Observations are seperated by a comma and the decimal is a point
1. Set the null and alternative hypothesis
1. Select the significance level (most of the time $\alpha = 0.05$)

In the results panel (on the right side or below depending on the size of your screen), you will see:

* a recap of your sample together with some appropriate descriptive statistics
* the confidence interval
* the hypothesis test
* the interpretation
* and an illustration of the hypothesis test

All formulas, steps and computations to arrive at the final results are also provided.

I hope you will find this app useful to do inferential statistics and in particular confidence interval and hypothesis testing. See all other articles related to Shiny [here](/tags/shiny/). As always, if you find a mistake/bug or if you have any questions do not hesitate to let me know in the comment section below, <a href="https://github.com/AntoineSoetewey/statsandr/issues" target="_blank" rel="noopener">raise an issue on GitHub</a> or [contact me](/contact/). Get updates every time a new article is published by [subscribing to this blog](/subscribe/).

