---
title: Chi-square test of independence by hand
author: Antoine Soetewey
date: '2020-01-27'
slug: chi-square-test-of-independence-by-hand
categories: []
tags:
  - Statistics
meta_img: image/image.png
# description: Description for the page.
output:
  blogdown::html_page:
    toc: true
    toc_depth: 6
draft: true
---

# Introduction

Chi-square tests of independence test whether two [qualitative variables](/blog/variable-types-and-examples/#qualitative) are independent, that is, whether there exists a relationship between the two variables of interest. In other words, this test is used to determine whether the values of one of the qualitative variables depend on the values of the other qualitative variable. If the test shows no association between the two variables (i.e., the variables are independent), it means that knowing the value of one variable gives no information about the value of the other variable. On the contrary, if the test shows a relationship between the variables (i.e., the variables are dependent), it means that knowing the value of one variable provides information about the value of the other variable.

This article focuses on how to perform a Chi-square test of independence by hand and how to interpret the results with a concrete example. To learn how to do this test in R, read the article "[Chi-square test of independence in R](/blog/chi-square-test-of-independence-in-r/)".

# Hypotheses

The Chi-square test of independence is a hypothesis test so it has a null ($H_0$) and an alternative hypothesis ($H_1$):

* $H_0$ : the variables are independent, there is **no** relationship between the two categorical variables. Knowing the value of one variable does not help to predict the value of the other variable
* $H_1$ : the variables are dependent, there is a relationship between the two categorical variables. Knowing the value of one variable helps to predict the value of the other variable

# How the test works?

The Chi-square test of independence works by comparing the observed frequencies (so the frequencies observed in your sample) to the frequencies expected if there was no relationship between the two categorical variables (so the expected frequencies if the null hypothesis was true). If the difference between the observed frequencies and the expected frequencies is **small**, we cannot reject the null hypothesis of independence and thus we cannot reject the fact that the two **variables are not related**. On the other hand, if the difference between the observed frequencies and the expected frequencies is **large**, we can reject the null hypothesis of independence and thus we can conclude that the two **variables are related**.

