---
title: Draw a word cloud with a Shiny app
author: Antoine Soetewey
date: '2020-01-07'
slug: draw-a-word-cloud-with-a-shiny-app
categories: []
tags:
  - Shiny
meta_img: image/image.png
# description: Description for the page.
output:
  blogdown::html_page:
    toc: false
# draft: true
---

Below a Shiny app to help you draw a word cloud:

* [Word cloud](https://antoinesoetewey.shinyapps.io/word-cloud/)

Word clouds are particularily useful as part of text mining analyses. Moreover, it is also useful to analyze string and character variables for any datasets.

# How to use this app?

* In **Word source** you can see two examples of word clouds with preloaded texts. If you want to use your own file, choose the option "Upload a file"
* When uploading a file, make sure to upload a .csv or .txt file
* If it is a .csv file, there should be only one column containing all words or sentences (see example files: [example.csv](https://www.antoinesoetewey.com/files/ihaveadream.csv) and [example.txt](https://www.antoinesoetewey.com/files/ihaveadream.txt))
* Choose the language of the text. Stop words in the chosen language will be automatically removed
* Numbers and punctuations will be automatically removed as well, regardless of the language
* You can remove specific words by specifying them after having clicked on "Remove specific words?". Indicate one word per line
* Change the default options in **Maximum number of words** and **Background color** if needed
* If you need to display this word cloud in your analyses, you can simply take a screenshot and include it in your document

I hope you will find this app useful to draw word clouds of your texts. If you want to learn more about Shiny apps in R, see all [articles related to Shiny](/tags/shiny/). As always, if you find a mistake/bug or if you have any questions do not hesitate to let me know in the comment section below, <a href="https://github.com/AntoineSoetewey/statsandr/issues" target="_blank" rel="noopener">raise an issue on GitHub</a> or [contact me](/contact/). Get updates everytime a new article is published by [subscribing to this blog](/subscribe/).