---
title: 'Fisher''s exact test in R: independence test for a small sample'
author: Antoine Soetewey
date: '2020-01-28'
slug: fisher-s-exact-test-in-r-independence-test-for-a-small-sample
categories: []
tags:
  - R
meta_img: image/image.png
# description: Description for the page.
output:
  blogdown::html_page:
    toc: true
    toc_depth: 6
draft: true
bibliography: bibliography.bib
---

# Introduction

After presenting the [Chi-square test of independence by hand](/blog/chi-square-test-of-independence-by-hand/) and [in R](/blog/chi-square-test-of-independence-in-r/), this article focuses on the Fisher's exact test.

Independence tests are used to determine if there is a significant relationship between two categorical variables. There exists two different types of independence test:

* the Chi-square test (the most common)
* the Fisher's exact test

On the one hand, the Chi-square test is used when the sample is large enough (in this case the $p$-value is an approximation that becomes exact when the sample becomes infinite, which is the case for many statistical tests). On the other hand, the Fisher's exact test is used when the sample is small (and in this case the $p$-value is exact and is not an approximation).

The literature indicates that the usual rule for deciding whether the $\chi^2$ approximation is good enough is that the Chi-square test is not appropriate when the **expected** values in one of the cells of a contingency table is less than 5, and in this case the Fisher exact test is preferred [@mccrum2008correct; @bower2003use]. Here we use an exact Fisher's test because at least one of the **expected** values in the contingency table is less than 5. The Fisher exact test has the same null and alternative assumptions as the $\chi^2$ independence test, i.e. :


Remember that one assumption of the Chi-square test of independence is that the **expected** frequencies in all groups are equal to or greater than 5. 

