---
title: Hello World!
author: Antoine Soetewey
date: '2019-12-16'
slug: hello-world
# categories:
#   - Miscellaneous
tags:
  - Miscellaneous
meta_img: image/image.png
# description: Description for the page.
output:
  blogdown::html_page:
    toc: false
# draft: true
---

This is the first post for the blog [Stats and R](/), just to introduce it. This blog aims at helping academics and professionals working with data to grasp important concepts in [statistics](/tags/statistics/) and to [apply them in R](/tags/r/).

The goal of this website is to make statistics easy to understand by illustrating with examples and using plain English. When possible, for all statistical concepts covered here, I also write an article on how to apply these concepts in R.

If you are new to this blog and to R, I invite you to start with the following articles:

* [How to install R and RStudio](/blog/how-to-install-r-and-rstudio/)
* [How to import an Excel file in RStudio](/blog/how-to-import-an-excel-file-in-rstudio/)
* [Descriptive statistics by hand](/blog/descriptive-statistics-by-hand/) or [in R](/blog/descriptive-statistics-in-r/)

You can also:

* See [all articles](/blog/) or [articles by categories](/tags/) for more advanced articles
* Learn more [about me](/about/)
* [Subscribe to this blog](/subscribe/) to receive updates everytime a new article is published

Thanks in advance for reading.

As always, if you have a question or a suggestion related to the topic covered in this article, please add it as a comment so other readers can benefit from the discussion. If you find a mistake or bug, you can inform me by <a href="https://github.com/AntoineSoetewey/statsandr/issues" target="_blank" rel="noopener">raising an issue on GitHub</a>. For all other requests, you can contact me [here](/contact/).

Get updates every time a new article is published by [subscribing to this blog](/subscribe/).

**Related articles:**

<?php
include("https://rss.bloople.net/?url=https%3A%2F%2Fwww.statsandr.com%2Findex.xml&detail=-1&limit=5&showtitle=false");
php?>
