---
title: How to import an Excel file in RStudio
author: Antoine Soetewey
date: '2019-12-18'
slug: how-to-import-an-excel-file-in-rstudio
categories: []
tags:
  - R
meta_img: image/image.png
# description: Description for the page.
output:
  blogdown::html_page:
    toc: true
draft: true
---

# Introduction

As we have seen in this article on [how to install R and RStudio](/blog/how-to-install-r-and-rstudio), R is useful for many kind of computational tasks and statistical analyses. However, it would not be so powerful and useful without the possibility to import datasets into R. As you will most likely use R with your own data, being able to import it into R is crucial for any user.

In this article I present two different ways to import an Excel file; one through the code and one in a more user-friendly way. I also discuss about the main advantages and inconvenients of both methods. Note that:

* How to import a dataset often depends on the format of the file (Excel, CSV, text, SPSS, Stata, etc.). I focus here only on Excel files as it is the most common type of file for a dataset,
* There are several other ways to import an Excel file (probably even some I am not aware of), but I present the two most simple yet robust ways to import such files,
* No matter what type of file and how you import it, there is one gold standard regarding how datasets are structured: columns correspond to variables and rows correspond to individuals (in the broad sense of the term). See more details on [how your data should be structured](/blog/how-to-structure-my-dataset/).

# Transform an Excel file to a CSV file

Before dealing with the importation, the first thing is to change the format of your Excel file to a CSV format. CSV format is the standard when working with datasets and programming languages as it is a more robust format compared to Excel. If your file is already in the CSV format (with the extension .csv), you can skip this section. If the file is not in the CSV format (for example the extension is .xlsx) you can easily transform it to CSV by following these steps:

1. Open your Excel file,
1. Click on File > Save as
1. Choose the format .csv
1. Click on Save

Check that your file finishes with the extension .csv. If that is the case, your file is now ready to be imported.

# R working directory

Although programming languages may be very powerful, it often needs our help and importing a dataset is not an exception. Indeed, before importing your data, you must tell RStudio where your file is located (so let RStudio know in which folder to look for your dataset). But before this, let me introduce the **working directory**. The working directory is the location (in your computer) of where RStudio is currently working (in fact RStudio is not working across your entire computer; it is working inside one folder of your computer). Concerning this working directory, there are two functions that we will need:

1. `getwd()` (`wd` stands for working directory),
1. `setwd()`.

In most cases, when you open RStudio, the working directory (so where it is currently working) is different than where your dataset is located. To know what is the working directory, use `getwd()`. On MacOS, this function will most likely render a location such as `"/Users/yourname/"`, while on Windows it will most likely render `"c:/Documents/"`. Do not worry if your working directory is different, the most important is to set the working directory correctly (so where your file is located) and not where it is now. 

## Set working directory

As mentioned earlier, your dataset is most likely located in a different location than your working directory. Without any action from you, RStudio will never be able to import your file as it is not looking in the correct folder. Now, in order to specify the correct location of your file (that is, to tell RStudio in which folder it should look for your dataset), you have two options:

1. the user-friendly method and
1. via the code (which you will see later why it is the preferred option).

### User-friendly method

To set the correct folder, so to set the working directory equal to the folder where your file is located, follow these steps:

1. In the lower right pane of RStudio, click on the tab "Files",
1. Click on "Home" next to the house icon,
1. Open the folder until you find your dataset,
1. Click on 

### Via the code

As always, if you find a mistake/bug or if you have any questions do not hesitate to let me know in the comment section below, <a href="https://github.com/AntoineSoetewey/statsandr/issues" target="_blank" rel="noopener">raise an issue on GitHub</a> or [contact me](/contact/).