---
title: How to install R and RStudio?
author: Antoine Soetewey
date: '2019-12-17'
slug: how-to-install-r-and-rstudio
categories: []
tags:
  - R
meta_img: image/image.png
# description: Description for the page.
output:
  blogdown::html_page:
    toc: true
draft: true
---

# What is R and RStudio?

**R** is nothing more than a programming language. At the time of writing, this language is (one of) the leading program in statistics, although not the only programming language used by statisticians.

In order to use R, we need two things:

* a text editor in which to write our code
* a place to run this code

You can download R at <a href="https://www.freestatistics.org/cran/" target="_blank">www.freestatistics.org/cran/</a>.

This is where RStudio comes handy. RStudio is an integrated development environment (IDE) for R. This software has the advantage of offering both a powerful text editor for writing your code and a place to run the code written in this editor (and I would add that it is more user-friendly). For these reasons, I highly recommend using RStudio instead of R. (Note that RStudio requires the prior installation of the R software provided by CRAN in order to be able to function properly. Just installing RStudio on your personal computer is not enough.)

You can download RStudio at <a href="https://www.rstudio.com" target="_blank">www.rstudio.com</a>.

# How to use RStudio?

Now that both programs are installed on your computer, let's dive into the main features of RStudio.




