---
title: "Inferential statistics: confidence intervals and hypothesis tests explained in 4 easy steps"
author: Antoine Soetewey
date: '2020-02-01'
slug: inferential-statistics-confidence-intervals-and-hypothesis-tests-explained-in-4-easy-steps
categories: []
tags:
  - Statistics
meta_img: image/image.png
# description: Description for the page.
output:
  blogdown::html_page:
    toc: true
    toc_depth: 6
draft: true
---

xxx add image and put the link in the YAML

# Introduction

Remember that [descriptive statistics](/blog/descriptive-statistics-by-hand) is a branch of statistics aiming at describing and summarizing a set of data in the best possible manner, that is, by reducing them down to a few meaningful key measures and visualizations (with as little loss of information as possible). In other words, descriptive statistics helps to have a better understanding and a clear image about a set of observations thanks to summary statistics and graphics. With descriptive statistics, there is no uncertainty because we describe only the group of observations that we decided to work on and no attempt is made to generalize the observed characteristics to another or to a larger group of observations.

Inferential statistics is another branch of statistics that uses a random sample of data taken from a population to make inferences, i.e., to draw conclusions about the population (see the [difference between population and sample](/blog/what-is-the-difference-between-population-and-sample/)). In other words, information from the sample is used to make generalizations about the parameter of interest in the population. Inferential statistics includes two important tools: hypothesis tests and confidence intervals.

As part of my teaching assistant position, I quickly realized that students often struggle to compute confidence intervals, perform hypothesis tests and interpret the results. It seems to me that students often encounter difficulties because this branch of statistics is rather unclear and abstract to them. I believe the main reason why it looks abstract to them is because they do not understand the final goal of inferential statistics, that is, the why behind these tools. They often perform hypothesis tests and confidence intervals by simply following the steps presented in another example whitout understanding the reasoning behind it, as they would follow a cooking recipe because they must prepare food, but not because they actually want to prepare *good* food.

For this reason, I though it would be useful to write an article on the goal of hypothesis tests and confidence intervals (the why), in which context they should be used (the when), how they work (in 4 easy steps) and how to interpret the results (as statistical results are meaningless without proper interpretation). Like anything else in statistics, it becomes much easier when we understand what we are trying to demonstrate before knowing how to compute it.

Inferential statistics can be applied to many parameters. Nonetheless, in order to keep this article easy and accessible to people from diverse backgrounds, I focus on hypothesis tests and confidences intervals applied to the 3 main parameters: **mean, proportion and variance**.

If you are familiar with these two tools, below are 3 articles that may be of interest to you:

* [Hypothesis tests and confidence intervals for one and two means (independent and paired samples)](/blog/xxx)
* [Hypothesis tests and confidence intervals for one and two proportions](/blog/xxx)
* [Hypothesis tests and confidence intervals for one and two variances](/blog/xxx)

The 3 articles above focus on the practical application of the two tools of inferential statistics by hand and in R. The present article covers the same topic but from a theoritical perspective in order to lay the foundations of hypothesis testing and confidence interval, with a special focus on the understanding and the reasoning behind the tools. I believe that grasping the concepts behind these tools from a theoritical perspective is of great help when applying them in practice.

# Hypothesis tests and confidence intervals: why and when?

Unlike descriptive statistics where we have describe only the data at hand, hypothesis tests and confidence intervals use a subset of observations (a sample) to draw conclusions about the population.

One may wonder why we would try to "guess" a parameter of a population based on a sample, instead of simply collecting the data for the entire population and compute the statistics we are interested in. The main reason why we actually use a sample instead of the population is because most of the time collecting the data on the entire population is impossible, too complex, too expensive, it would take too long, or a combination of any of these reasons. Suppose a researcher wants to test if Belgian women are taller than French women. Suppose a health professional would like to know whether the proportion of smokers is the same among athletes and non-athletes. It would take way too long to measure the height of all Belgian and French women and to ask all athletes and non-athletes if they smoke or not.
For these reasons, we simply xxx

Thanks for reading. I hope this article helped you to understand better how to perform hypothesis tests and construct confidence intervals by hand.

As always, if you have a question or a suggestion related to the topic covered in this article, please add it as a comment so other readers can benefit from the discussion. If you find a mistake or bug, you can inform me by <a href="https://github.com/AntoineSoetewey/statsandr/issues" target="_blank" rel="noopener">raising an issue on GitHub</a>. For all other requests, you can contact me [here](/contact/).

Get updates every time a new article is published by [subscribing to this blog](/subscribe/).

**Related articles:**

<script src="//rss.bloople.net/?url=https%3A%2F%2Fwww.statsandr.com%2Ftags%2Fstatistics%2Findex.xml&detail=-1&limit=5&showtitle=false&type=js"></script>
