---
title: A practial guide on optimal asset allocation
author: Antoine Soetewey
date: '2020-01-07'
slug: practical-guide-on-optimal-asset-allocation
categories: []
tags:
  - Shiny
  - Finance
meta_img: image/image.png
# description: Description for the page.
output:
  blogdown::html_page:
    toc: false
# draft: true
---

In his book *A Random Walk Down Wall Street*, Burton G. Malkiel advises readers of an optimal asset allocation depending on age. As an amateur investor, I thought it would be useful to develop a Shiny app which depicts his advices for other interested investors. Here is the app:

* [Optimal asset allocation](https://antoinesoetewey.shinyapps.io/optimal-asset-allocation/)

# How to use this app?

1. Open the app via this [link](https://antoinesoetewey.shinyapps.io/optimal-asset-allocation/)
1. Set your age under **How old are you?**
1. Indicate how much you are willing to invest

On the right panel (or below depending on the size of your screen) you will see a table and a barplot. The table includes:

* the different type of assets which represent the different allocations
* the most common tickers for each type of asset
* the optimal percentage for each asset
* the optimal amount for each asset

In the table, the optimal percentage depends on your age (the older you are, the more conservative your portfolio), while the optimal amount depends on your age and the amount you are willing to invest.

The barplot displays the optimal weight (so the optimal percentage of your portfolio) for each type of asset: stocks, bonds, real estate and cash. This is just a visualization of the column "Optimal percentage" displayed in the table above.

It is also possible to compare your portfolio with the optimal portfolio, as recommended by the author. For this comparison, click on the tab "Compare with your portfolio" above **How old are you?**. In this tab:

1. Again, indicate your age
1. Then indicate your portfolio's value for each asset (if you do not own a specific asset, leave it equal to 0)

On the right panel (or below depending on the size of your screen) you will see your portfolio's total amount and a barplot comparing your portfolio and the optimal portfolio according to your age. This visualization will instantly give you a clear overview of what type of asset is overrepresented and underrepresented in your current portfolio compared the the optimal one. This will allow you to easily see how to rebalance your assets in accordance to what the author suggests.

*Disclosure: Note that this practical guide on asset allocation is based on the book A Random Walk Down Wall Street by Burton G. Malkiel. This application does not include investment advice or recommendations, nor a financial analysis. This application is intended for information only and you invest at your own risks. I cannot be held liable for any decision made based on the information contained in this application, nor for its use by third parties.*

I hope you will find this app useful to quickly replicate the optimal asset allocation suggested by Burton G. Malkiel in his book *A Random Walk Down Wall Street*. If you want to have more information about this investment strategy, I suggest reading his book. If you want to learn more about Shiny apps in R, see all [articles related to Shiny](/tags/shiny/). As always, if you find a mistake/bug or if you have any questions do not hesitate to let me know in the comment section below, <a href="https://github.com/AntoineSoetewey/statsandr/issues" target="_blank" rel="noopener">raise an issue on GitHub</a> or [contact me](/contact/). Get updates everytime a new article is published by [subscribing to this blog](/subscribe/).
