---
title: The 7 concepts and formulas in probability that every data scientist should know
author: Antoine Soetewey
date: '2020-03-03'
slug: the-7-concepts-and-formulas-in-probability-that-every-data-scientist-should-know
categories: []
tags:
  - Basics
  - Probability
  - R
  - Statistics
meta_img: image/image.png
description: xxx
output:
  blogdown::html_page:
    toc: true
    toc_depth: 6
draft: true
---

xxx add image

# What is probability?

Probability is the likelihood of an event occurring; it is a mathematical model to describe random phenomena. In other words, probability is a branch of mathematics that provides models to describe random processes. These mathematical tools allow to establish theoretical models for random phenomena and to use them to make predictions. Like every model, the probabilistic model is a simplification of the world. However, the model is useful as soon as it captures the essential features.

In this article, we present xxx fundamental formulas and conceps in probability to get you started in data science.

# 1. A probability is always between 0 and 1

The probability of an event is always between 0 and 1,

$$0 \le P(A) \le 1$$

* If an event is impossible: *P(A) = 0*
* If an event is certain: *P(A) = 1*

For example, throwing a 7 with a standard dice (with faces from 1 to 6) is impossible so its probability is equal to 0. Throwing any number from 1 to 6 with a dice is certain, so its probability is equal to 1.

# 2. Compute a probability

The probability of an event occurring is equal to the number of favourable cases (number of ways it can happen) divided by the number of possible cases (total number of outcomes):

$$P(A) = \frac{\text{number of favourable cases}}{\text{number of possible cases}}$$

For example, the probability of rolling a 3 with a dice is

$$P(3) = \frac{\text{number of favourable cases}}{\text{number of possible cases}} = \frac{1}{6}$$

because there is only one favourable case (there is only one face with a 3 on it), and there are 6 possible cases (because there are 6 faces altogether).

# 3. Complement of an event

The probability of the complement (or opposite) of an event is:

$$P(\text{not A}) = P(\bar{A}) = 1 - P(A)$$

# 4. Union of two events

The probability of the union of two events is the probability of either occurring:

$$P(\text{A or B)} = P(A \cup B) = P(A) + P(B) - P(A \cap B)$$

Suppose that the probability of a fire breaking out in two houses in a given year is:

* in house A: 60%
* in house B: 45%
* in at least one of the two houses: 80%

Graphically we have

```{r, echo = FALSE, message = FALSE, warning = FALSE}
# install.packages('VennDiagram')
library(VennDiagram)

venn.plot <- draw.pairwise.venn(0.6, 0.45, 0.25, category = c("House A", "House B"), lty = rep("blank", 
    2), fill = c("light blue", "pink"), alpha = rep(0.5, 2), cat.pos = c(0, 
    0), cat.dist = rep(0.025, 2))
grid.draw(venn.plot)
```

The probability of a fire breaking out in house A **or** house B is

$$P(A \cup B) = P(A) + P(B) - P(A \cap B) = 0.6 + 0.45 - 0.25 = 0.8$$

By summing P(A) and P(B), the intersection of A and B is counted twice. This is the reason we subtract it to count it only once.

If two events are mutually exclusive (i.e., two events that cannot occur at the same time), the probability of both events occuring is equal to 0, so the above formula becomes

$$P(A \cup B) = P(A) + P(B)$$

For example, the probability of rolling a 3 or 6 on a six-sided dice is

$$P(3 \cup 6) = P(3) + P(6) = \frac{1}{6} + \frac{1}{6} = \frac{1}{3}$$

# 5. Intersection of two events

If two events are independent, the probability of the intersection of two events (i.e., the joint probability) is the probability of the two events occuring:

$$P(\text{A and B)} = P(A \cap B) = P(A) * P(B)$$

For instance, if two coins are flipped, the probability of both being tails is

$$P(T_1 \cap T_2) = P(T_1) * P(T_2) = \frac{1}{2} * \frac{1}{2} = \frac{1}{4}$$

# 6. Independence of two events

The independence of two events can be verified thanks to the above formula. If the equality holds, the two events are said to be independent, otherwise the two events are said to be dependent.

* In the example of the two coins:

$$P(T_1 \cap T_2) = \frac{1}{4}$$

and

$$P(T_1) * P(T_2) = \frac{1}{2} * \frac{1}{2} = \frac{1}{4}$$

so the following equality holds

$$P(T_1 \cap T_2) = P(T_1) * P(T_2) = \frac{1}{4}$$

The two events are thus independent, denoted $T_1{\perp\!\!\!\perp}T_2$.

* In the example of the fire breaking out in two houses (see [section 4](/blog/the-7-concepts-and-formulas-in-probability-that-every-data-scientist-should-know/#)):

$$P(A \cap B) = 0.25$$

and

$$P(A) * P(B) = 0.6 \cdot 0.45 = 0.27$$

so the following equality does not hold

$$P(A \cap B) \ne P(A) * P(B)$$

The two events are thus dependent, denoted $A \not\!\perp\!\!\!\perp B$.

# 6. Conditional probability



