---
title: Tips and tricks in R and R Markdown
author: Antoine Soetewey
date: '2020-01-15'
slug: tips-and-tricks-in-r-and-r-markdown
categories: []
tags:
  - R Markdown
  - R
meta_img: image/image.png
# description: Description for the page.
output:
  blogdown::html_page:
    toc: true
    toc_depth: 6
draft: true
---

If you have the chance to work with an experienced programmer, you may be amazed by how fast she can write code. In this article, I share some tips, tricks and shortcuts you can use in R and R Markdown to speed up the writing of your code. 

# Ordered list

In R Markdown, when creating an ordered list such as this one:

1. Item 1
1. Item 2
1. Item 3

Instead of bothering with the numbers and typing

```
1. Item 1
2. Item 2
3. Item 3
```

you can simply type

```
1. Item 1
1. Item 2
1. Item 3
```

for the exact same result (try it yourself or check the code of this article!). This way you do not need to know which number is next when creating a new item.

To go feven further, any numeric will actually render the same result as long as the first item is the number you want to start from. For example, you could type:

```
1. Item 1
7. Item 2
3. Item 3
```

which renders

1. Item 1
7. Item 2
3. Item 3

However, I suggest always using the number you want to start from for all items because if you move one item at the top, the list will start with this new number. For instance, if we move `7. Item 2` from the previous list at the top, it becomes:

```
7. Item 2
1. Item 1
3. Item 3
```

which incorrectly renders

7. Item 2
1. Item 1
3. Item 3

# Shortcut for new code chunks

ctrl + option + i for new code chunk

# check snippets : https://rviews.rstudio.com/2017/03/03/february-17-tips-and-tricks/
# check shortcuts : https://statistique-et-logiciel-r.com/huit-raccourcis-clavier-a-utiliser-sous-r-studio/

