---
title: Variable types
author: Antoine Soetewey
date: '2019-12-30'
slug: variable-types-and-examples
# categories: []
tags:
  - Statistics
meta_img: image/image.png
# description: Description for the page.
output:
  blogdown::html_page:
    toc: true
draft: true
---

# Big picture

In statistics, variables are classified into 4 different types:

```{r, echo = FALSE}
library(data.tree)

acme <- Node$new("Variable")
  quali <- acme$AddChild("Qualitative")
    nominal <- quali$AddChild("Nominal")
    ordinal <- quali$AddChild("Ordinal")
  quanti <- acme$AddChild("Quantitative")
    discr <- quanti$AddChild("Discrete")
    cont <- quanti$AddChild("Continuous")
    

SetNodeStyle(acme, style = "filled,rounded", shape = "box", fillcolor = "LightGray", 
            fontname = "helvetica", tooltip = GetDefaultTooltip)

plot(acme)
```

# Quantitative

A quantitative variable is a variable that reflects a notion of magnitude, that is, if the values it can take are numbers. A quantitative variable represents thus a measure and is numerical.

## Discrete

Quantitative discrete variables are variables for which the values it can take are **countable** and have a **finite number of possibilities**. The values are often (but not always) integers. Here are some examples of discrete variables:

* Number of children per family
* Number of students in a class
* Number of citizens of a country

Even if it would take a long time to count the citizens of a large country, it is still doable. Moreover, for all examples, the number of possibilites is finite. Whatever the number of children in a family, it will never be 3.58 or 7.912 so the number of possibilities is a finite number.

## Continuous

On the other hand, continuous variables are variables for which the values are **not countable** and have a **infinite number of possibilities**. For example:

* The age
* The weight
* The height

For simplicity, we usually referred to years, kilograms (or pounds) and centimeters (or feet and inches) for age, weight and height respectively. However, a 28-year-old man could actually be 28 years, 7 months, 16 days, 3 hours, 4 minutes, 5 seconds, 31 milliseconds, 9 nanoseconds old. For all measurements, we usually stop at a standard level of granularity, but nothing (except our measurement tools) prevents us from going deeper, leading to an infinite number of potential values. The fact that the values can take an infinite number of possibilities makes it uncountable.

# Qualitative

In opposition to quantitative variables, qualitative variables (also referred as categorical variables or factors) are variables that are not numerical and which values fits into categories. In other words, a qualitative variable is a variable which takes as its value modalities, categories or even levels, in contrast to quantitative variables which measure a quantity on each individual.

# Nominal

A nominal variable is a qualitative variable where no ordering is possible or implied in the levels. For example, the variable gender is nominal because there is no order in the levels female/male. Eye color is another example of nominal variable because there is no order among blue, brown or green eyes. A nominal variable can have two levels (e.g., do you smoke? Yes/No or what is your gender? Female/Male) or a large number of levels (what is your university? Each university is a level in that case).

# Ordinal



