<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title> Outliers detection in R - Stats and R </title>
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">
    <meta name="referrer" content="no-referrer">
    <meta name="description" content="Learn how to detect outliers in R thanks to descriptive statistics and via the Hampel filter, the Grubbs, the Dixon and the Rosner tests for outliers" />
    <meta property="og:site_name" content="Stats and R" />
    <meta property="og:locale" content="en_US" />
    <meta property="og:type" content="article" />
    <meta property="og:url" content="/blog/outliers-detection-in-r/" />
    <meta property="og:title" content="Outliers detection in R" />
    <meta property="og:image" content="/blog/2020-08-11-outliers-detection-in-r_files/outliers-detection-in-R.jpeg" />
    <meta property="og:description" content="Learn how to detect outliers in R thanks to descriptive statistics and via the Hampel filter, the Grubbs, the Dixon and the Rosner tests for outliers" />

    <meta name="twitter:card" content="summary_large_image" />
    
    <meta name="twitter:site" content="@statsandr">
    <meta name="twitter:creator" content="@statsandr">
    
    <meta name="twitter:title" content="Outliers detection in R" />
    <meta name="twitter:description" content="Learn how to detect outliers in R thanks to descriptive statistics and via the Hampel filter, the Grubbs, the Dixon and the Rosner tests for outliers" />
    <meta name="twitter:image" content="/blog/2020-08-11-outliers-detection-in-r_files/outliers-detection-in-R.jpeg" />

    <link rel="canonical" href="/blog/outliers-detection-in-r/">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha256-aAr2Zpq8MZ+YA/D6JtRD3xtrwpEz2IqOS+pWD/7XKIw=" crossorigin="anonymous" />

    <link rel="stylesheet" href="/css/custom.css" />

    
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.14.2/styles/tomorrow.min.css" integrity="sha256-0QU8ry64q+N6YBIEF/6XF6vUeF15gbNO4tLS6ikk0FI=" crossorigin="anonymous" />
    

    

    <link rel="shortcut icon"
        href="/image/favicon.png">

    
        <link href="/index.xml" rel="alternate" type="application/rss+xml" title="Stats and R" />
    
</head>

<body>
    
    <div class="my-4 my-md-5 header">
    <div class="container">
        <div class="row">
            <div class="col-auto offset-md-1 d-none d-md-block">
                
                    <a href="/">
                        <img class="ml-md-4 logo img-fluid d-block rounded-circle" src="/image/avatar.jpg" alt="logo">
                    </a>
                
            </div>
            <div class="col-auto align-self-center mr-auto">
                <a href="/">
                    <h1 class="name">Stats and R</h1>
                </a>

                <ul class="nav nav-primary">
                    
                        <li class="nav-item">
                            <a class="text-uppercase nav-link text-blog" href="/blog/">
                                
                                Blog
                            </a>
                        </li>
                    
                        <li class="nav-item">
                            <a class="text-uppercase nav-link text-tags" href="/tags/">
                                
                                Tags
                            </a>
                        </li>
                    
                        <li class="nav-item">
                            <a class="text-uppercase nav-link text-about" href="/about/">
                                
                                About
                            </a>
                        </li>
                    
                        <li class="nav-item">
                            <a class="text-uppercase nav-link text-newsletter" href="/subscribe/">
                                
                                Newsletter
                            </a>
                        </li>
                    
                        <li class="nav-item">
                            <a class="text-uppercase nav-link text-contact" href="/contact/">
                                
                                Contact
                            </a>
                        </li>
                    

                    
                </ul>

            </div>
        </div>
    </div>
</div>


    <div class="content">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-sm-12 col-md-10">
                    <h1 class="mx-0 mx-md-4 blog-post-title">Outliers detection in R</h1>

                    <div class="mb-md-4 meta">
                        
                            
                                <span class="author" title="Antoine Soetewey">
                                    Antoine Soetewey
                                </span>
                            
                        

                        <span class="date middot" title='Tue Aug 11 2020 00:00:00 UTC'>
                            2020-08-11
                        </span>

                        <span class="reading-time middot">
                            20 minute read
                        </span>

                        <div class="d-none d-md-inline tags">
                            <ul class="list-unstyled d-inline">
                                
                                    <li class="d-inline middot">
                                        <a href="/tags/r">R</a>
                                    </li>
                                
                                    <li class="d-inline middot">
                                        <a href="/tags/statistics">Statistics</a>
                                    </li>
                                
                            </ul>
                        </div>

                        <div class="d-none d-md-inline tags">
                            <ul class="list-unstyled d-inline">
                                
                                
                            </ul>
                        </div>
                    </div>

                    <div class="markdown">
                        
    

<div id="TOC">
<ul>
<li><a href="#introduction">Introduction</a></li>
<li><a href="#descriptive-statistics">Descriptive statistics</a><ul>
<li><a href="#minimum-and-maximum">Minimum and maximum</a></li>
<li><a href="#histogram">Histogram</a></li>
<li><a href="#boxplot">Boxplot</a></li>
<li><a href="#percentiles">Percentiles</a></li>
</ul></li>
<li><a href="#hampel-filter">Hampel filter</a></li>
<li><a href="#statistical-tests">Statistical tests</a><ul>
<li><a href="#grubbss-test">Grubbs’s test</a></li>
<li><a href="#dixons-test">Dixon’s test</a></li>
<li><a href="#rosners-test">Rosner’s test</a></li>
</ul></li>
<li><a href="#additional-remarks">Additional remarks</a></li>
<li><a href="#reference">Reference</a></li>
</ul>
</div>

<p><img src="/blog/2020-08-11-outliers-detection-in-r_files/outliers-detection-in-R.jpeg" style="width:100.0%" /></p>
<div id="introduction" class="section level1">
<h1>Introduction</h1>
<p>An <strong>outlier</strong> is a value or an <strong>observation that is distant from other observations</strong>, that is to say, a data point that differs significantly from other data points. <span class="citation">Enderlein (1987)</span> goes even further as the author considers outliers as values that deviate so much from other observations one might suppose a different underlying sampling mechanism.</p>
<p>An observation must always be compared to other observations made on the same phenomenon before actually calling it an outlier. Indeed, someone who is 200 cm tall (6’7" in US) will most likely be considered as an outlier compared to the general population, but that same person may not be considered as an outlier if we measured the height of basketball players.</p>
<p>An outlier may be due to the variability inherent in the observed phenomenon. For example, it is often the case that there are outliers when collecting data on salaries, as some people make much more money than the rest. Outliers can also arise due to an experimental, measurement or encoding error. For instance, a human weighting 786 kg (1733 pounds) is clearly an error when encoding the weight of the subject. Her or his weight is most probably 78.6 kg (173 pounds) or 7.86 kg (17 pounds) depending on whether weights of adults or babies have been measured.</p>
<p>For this reason, it sometimes makes sense to formally distinguish two classes of outliers: (i) extreme values and (ii) mistakes. Extreme values are statistically and philosophically more interesting, because they are possible but unlikely responses. (Thanks Felix Kluxen for the valuable suggestion.)</p>
<p>In this article, I present several approaches to detect outliers in R, from simple techniques such as <a href="/blog/descriptive-statistics-in-r/">descriptive statistics</a> (including minimum, maximum, histogram, boxplot and percentiles) to more formal techniques such as the Hampel filter, the Grubbs, the Dixon and the Rosner tests for outliers.</p>
<p>Although there is no strict or unique rule whether outliers should be removed or not from the dataset before doing statistical analyses, it is quite common to, at least, remove or impute outliers that are due to an experimental or measurement error (like the weight of 786 kg (1733 pounds) for a human). Some statistical tests require the absence of outliers in order to draw sound conclusions, but removing outliers is not recommended in all cases and must be done with caution.</p>
<p>This article will not tell you whether you should remove outliers or not (nor if you should impute them with the median, mean, mode or any other value), but it will help you to detect them in order to, as a first step, verify them. After their verification, it is then your choice to exclude or include them for your analyses (and this usually requires a thoughtful reflection on the researcher’s side). Removing or keeping outliers mostly depend on three factors:</p>
<ol style="list-style-type: decimal">
<li>The domain/context of your analyses and the research question. In some domains, it is common to remove outliers as they often occur due to a malfunctioning process. In other fields, outliers are kept because they contain valuable information. It also happens that analyses are performed twice, once with and once without outliers to evaluate their impact on the conclusions. If results change drastically due to some influential values, this should caution the researcher to make overambitious claims.</li>
<li>Whether the tests you are going to apply are robust to the presence of outliers or not. For instance, the slope of a simple linear regression may significantly varies with just one outlier, whereas non-parametric tests such as the <a href="/blog/wilcoxon-test-in-r-how-to-compare-2-groups-under-the-non-normality-assumption/">Wilcoxon test</a> are usually robust to outliers.</li>
<li>How distant are the outliers from other observations? Some observations considered as outliers (according to the techniques presented below) are actually not really extreme compared to all other observations, while other potential outliers may be really distant from the rest of the observations.</li>
</ol>
<p>The dataset <code>mpg</code> from the <code>{ggplot2}</code> package will be used to illustrate the different approaches of outliers detection in R, and in particular we will focus on the variable <code>hwy</code> (highway miles per gallon).</p>
</div>
<div id="descriptive-statistics" class="section level1">
<h1>Descriptive statistics</h1>
<div id="minimum-and-maximum" class="section level2">
<h2>Minimum and maximum</h2>
<p>The first step to detect outliers in R is to start with some <a href="/blog/descriptive-statistics-in-r/">descriptive statistics</a>, and in particular with the <a href="/blog/descriptive-statistics-in-r/#minimum-and-maximum">minimum and maximum</a>.</p>
<p>In R, this can easily be done with the <code>summary()</code> function:</p>
<pre class="r"><code>dat &lt;- ggplot2::mpg
summary(dat$hwy)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   12.00   18.00   24.00   23.44   27.00   44.00</code></pre>
<p>where the minimum and maximum are respectively the first and last values in the output above. Alternatively, they can also be computed with the <code>min()</code> and <code>max()</code> functions:</p>
<pre class="r"><code>min(dat$hwy)</code></pre>
<pre><code>## [1] 12</code></pre>
<pre class="r"><code>max(dat$hwy)</code></pre>
<pre><code>## [1] 44</code></pre>
<p>Some clear encoding mistake like a weight of 786 kg (1733 pounds) for a human will already be easily detected by this very simple technique.</p>
</div>
<div id="histogram" class="section level2">
<h2>Histogram</h2>
<p>Another basic way to detect outliers is to draw a <a href="/blog/descriptive-statistics-in-r/#histogram">histogram</a> of the data.</p>
<p>Using R base (with the number of bins corresponding to the square root of the number of observations in order to have more bins than the default option):</p>
<pre class="r"><code>hist(dat$hwy,
  xlab = &quot;hwy&quot;,
  main = &quot;Histogram of hwy&quot;,
  breaks = sqrt(nrow(dat))
) # set number of bins</code></pre>
<p><img src="/blog/2020-08-11-outliers-detection-in-r_files/figure-html/unnamed-chunk-3-1.png" width="100%" style="display: block; margin: auto;" /></p>
<p>or using <code>ggplot2</code> (learn how to create plots with this package via the <a href="/blog/rstudio-addins-or-how-to-make-your-coding-life-easier/#esquisse"><code>esquisse</code> addin</a> or via this <a href="/blog/graphics-in-r-with-ggplot2/">tutorial</a>):</p>
<pre class="r"><code>library(ggplot2)

ggplot(dat) +
  aes(x = hwy) +
  geom_histogram(bins = 30L, fill = &quot;#0c4c8a&quot;) +
  theme_minimal()</code></pre>
<p><img src="/blog/2020-08-11-outliers-detection-in-r_files/figure-html/unnamed-chunk-4-1.png" width="100%" style="display: block; margin: auto;" /></p>
<p>From the histogram, there seems to be a couple of observations higher than all other observations (see the bar on the right side of the plot).</p>
</div>
<div id="boxplot" class="section level2">
<h2>Boxplot</h2>
<p>In addition to histograms, <a href="/blog/descriptive-statistics-in-r/#boxplot">boxplots</a> are also useful to detect potential outliers.</p>
<p>Using R base:</p>
<pre class="r"><code>boxplot(dat$hwy,
  ylab = &quot;hwy&quot;
)</code></pre>
<p><img src="/blog/2020-08-11-outliers-detection-in-r_files/figure-html/unnamed-chunk-5-1.png" width="100%" style="display: block; margin: auto;" /></p>
<p>or using <code>ggplot2</code>:</p>
<pre class="r"><code>ggplot(dat) +
  aes(x = &quot;&quot;, y = hwy) +
  geom_boxplot(fill = &quot;#0c4c8a&quot;) +
  theme_minimal()</code></pre>
<p><img src="/blog/2020-08-11-outliers-detection-in-r_files/figure-html/unnamed-chunk-6-1.png" width="100%" style="display: block; margin: auto;" /></p>
<p>A boxplot helps to visualize a quantitative variable by displaying five common location summary (minimum, median, first and third quartiles and maximum) and any observation that was classified as a suspected outlier using the <a href="/blog/descriptive-statistics-in-r/#interquartile-range">interquartile range (IQR)</a> criterion. The IQR criterion means that all observations above <span class="math inline">\(q_{0.75} + 1.5 \cdot IQR\)</span> or below <span class="math inline">\(q_{0.25} - 1.5 \cdot IQR\)</span> (where <span class="math inline">\(q_{0.25}\)</span> and <span class="math inline">\(q_{0.75}\)</span> correspond to first and third quartile respectively, and IQR is the difference between the third and first quartile) are considered as potential outliers by R. In other words, all observations outside of the following interval will be considered as potential outliers:</p>
<p><span class="math display">\[I = [q_{0.25} - 1.5 \cdot IQR; q_{0.75} + 1.5 \cdot IQR]\]</span></p>
<p>Observations considered as potential outliers by the IQR criterion are displayed as points in the boxplot. Based on this criterion, there are 2 potential outliers (see the 2 points above the vertical line, at the top of the boxplot).</p>
<p>Remember that it is not because an observation is considered as a potential outlier by the IQR criterion that you should remove it. Removing or keeping an outlier depends on (i) the context of your analysis, (ii) whether the tests you are going to perform on the dataset are robust to outliers or not, and (iii) how far is the outlier from other observations.</p>
<p>It is also possible to extract the values of the potential outliers based on the IQR criterion thanks to the <code>boxplot.stats()$out</code> function:</p>
<pre class="r"><code>boxplot.stats(dat$hwy)$out</code></pre>
<pre><code>## [1] 44 44 41</code></pre>
<p>As you can see, there are actually 3 points considered as potential outliers: 2 observations with a value of 44 and 1 observation with a value of 41.</p>
<p>Thanks to the <code>which()</code> function it is possible to extract the row number corresponding to these outliers:</p>
<pre class="r"><code>out &lt;- boxplot.stats(dat$hwy)$out
out_ind &lt;- which(dat$hwy %in% c(out))
out_ind</code></pre>
<pre><code>## [1] 213 222 223</code></pre>
<p>With this information you can now easily go back to the specific rows in the dataset to verify them, or print all variables for these outliers:</p>
<pre class="r"><code>dat[out_ind, ]</code></pre>
<pre><code>## # A tibble: 3 x 11
##   manufacturer model   displ  year   cyl trans   drv     cty   hwy fl    class  
##   &lt;chr&gt;        &lt;chr&gt;   &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt;   &lt;chr&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt; &lt;chr&gt;  
## 1 volkswagen   jetta     1.9  1999     4 manual… f        33    44 d     compact
## 2 volkswagen   new be…   1.9  1999     4 manual… f        35    44 d     subcom…
## 3 volkswagen   new be…   1.9  1999     4 auto(l… f        29    41 d     subcom…</code></pre>
<p>It is also possible to print the values of the outliers directly on the boxplot with the <code>mtext()</code> function:</p>
<pre class="r"><code>boxplot(dat$hwy,
  ylab = &quot;hwy&quot;,
  main = &quot;Boxplot of highway miles per gallon&quot;
)
mtext(paste(&quot;Outliers: &quot;, paste(out, collapse = &quot;, &quot;)))</code></pre>
<p><img src="/blog/2020-08-11-outliers-detection-in-r_files/figure-html/unnamed-chunk-10-1.png" width="100%" style="display: block; margin: auto;" /></p>
</div>
<div id="percentiles" class="section level2">
<h2>Percentiles</h2>
<p>This method of outliers detection is based on the <a href="/blog/descriptive-statistics-by-hand/#a-note-on-deciles-and-percentiles">percentiles</a>. With the percentiles method, all observations that lie outside the interval formed by the 2.5 and 97.5 percentiles will be considered as potential outliers. Other percentiles such as the 1 and 99, or the 5 and 95 percentiles can also be considered to construct the interval.</p>
<p>The values of the lower and upper percentiles (and thus the lower and upper limits of the interval) can be computed with the <code>quantile()</code> function:</p>
<pre class="r"><code>lower_bound &lt;- quantile(dat$hwy, 0.025)
lower_bound</code></pre>
<pre><code>## 2.5% 
##   14</code></pre>
<pre class="r"><code>upper_bound &lt;- quantile(dat$hwy, 0.975)
upper_bound</code></pre>
<pre><code>##  97.5% 
## 35.175</code></pre>
<p>According to this method, all observations below 14 and above 35.175 will be considered as potential outliers. The row numbers of the observations outside of the interval can then be extracted with the <code>which()</code> function:</p>
<pre class="r"><code>outlier_ind &lt;- which(dat$hwy &lt; lower_bound | dat$hwy &gt; upper_bound)
outlier_ind</code></pre>
<pre><code>##  [1]  55  60  66  70 106 107 127 197 213 222 223</code></pre>
<p>Then their values of highway miles per gallon can be printed:</p>
<pre class="r"><code>dat[outlier_ind, &quot;hwy&quot;]</code></pre>
<pre><code>## # A tibble: 11 x 1
##      hwy
##    &lt;int&gt;
##  1    12
##  2    12
##  3    12
##  4    12
##  5    36
##  6    36
##  7    12
##  8    37
##  9    44
## 10    44
## 11    41</code></pre>
<p>Alternatively, all variables for these outliers can be printed:</p>
<pre class="r"><code>dat[outlier_ind, ]</code></pre>
<pre><code>## # A tibble: 11 x 11
##    manufacturer model    displ  year   cyl trans  drv     cty   hwy fl    class 
##    &lt;chr&gt;        &lt;chr&gt;    &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt;  &lt;chr&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt; &lt;chr&gt; 
##  1 dodge        dakota …   4.7  2008     8 auto(… 4         9    12 e     pickup
##  2 dodge        durango…   4.7  2008     8 auto(… 4         9    12 e     suv   
##  3 dodge        ram 150…   4.7  2008     8 auto(… 4         9    12 e     pickup
##  4 dodge        ram 150…   4.7  2008     8 manua… 4         9    12 e     pickup
##  5 honda        civic      1.8  2008     4 auto(… f        25    36 r     subco…
##  6 honda        civic      1.8  2008     4 auto(… f        24    36 c     subco…
##  7 jeep         grand c…   4.7  2008     8 auto(… 4         9    12 e     suv   
##  8 toyota       corolla    1.8  2008     4 manua… f        28    37 r     compa…
##  9 volkswagen   jetta      1.9  1999     4 manua… f        33    44 d     compa…
## 10 volkswagen   new bee…   1.9  1999     4 manua… f        35    44 d     subco…
## 11 volkswagen   new bee…   1.9  1999     4 auto(… f        29    41 d     subco…</code></pre>
<p>There are 11 potential outliers according to the percentiles method. To reduce this number, you can set the percentiles to 1 and 99:</p>
<pre class="r"><code>lower_bound &lt;- quantile(dat$hwy, 0.01)
upper_bound &lt;- quantile(dat$hwy, 0.99)

outlier_ind &lt;- which(dat$hwy &lt; lower_bound | dat$hwy &gt; upper_bound)

dat[outlier_ind, ]</code></pre>
<pre><code>## # A tibble: 3 x 11
##   manufacturer model   displ  year   cyl trans   drv     cty   hwy fl    class  
##   &lt;chr&gt;        &lt;chr&gt;   &lt;dbl&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt;   &lt;chr&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt; &lt;chr&gt;  
## 1 volkswagen   jetta     1.9  1999     4 manual… f        33    44 d     compact
## 2 volkswagen   new be…   1.9  1999     4 manual… f        35    44 d     subcom…
## 3 volkswagen   new be…   1.9  1999     4 auto(l… f        29    41 d     subcom…</code></pre>
<p>Setting the percentiles to 1 and 99 gives the same potential outliers as with the IQR criterion.</p>
</div>
</div>
<div id="hampel-filter" class="section level1">
<h1>Hampel filter</h1>
<p>Another method, known as Hampel filter, consists of considering as outliers the values outside the interval (<span class="math inline">\(I\)</span>) formed by the median, plus or minus 3 median absolute deviations (<span class="math inline">\(MAD\)</span>):<a href="#fn1" class="footnote-ref" id="fnref1"><sup>1</sup></a></p>
<p><span class="math display">\[I = [median - 3 \cdot MAD; median + 3 \cdot MAD]\]</span></p>
<p>where <span class="math inline">\(MAD\)</span> is the median absolute deviation and is defined as the median of the absolute deviations from the data’s median <span class="math inline">\(\tilde{X} = median(X)\)</span>:</p>
<p><span class="math display">\[MAD = median(|X_i - \tilde{X}|)\]</span></p>
<p>For this method we first set the interval limits thanks to the <code>median()</code> and <code>mad()</code> functions:</p>
<pre class="r"><code>lower_bound &lt;- median(dat$hwy) - 3 * mad(dat$hwy)
lower_bound</code></pre>
<pre><code>## [1] 1.761</code></pre>
<pre class="r"><code>upper_bound &lt;- median(dat$hwy) + 3 * mad(dat$hwy)
upper_bound</code></pre>
<pre><code>## [1] 46.239</code></pre>
<p>According to this method, all observations below 1.761 and above 46.239 will be considered as potential outliers. The row numbers of the observations outside of the interval can then be extracted with the <code>which()</code> function:</p>
<pre class="r"><code>outlier_ind &lt;- which(dat$hwy &lt; lower_bound | dat$hwy &gt; upper_bound)
outlier_ind</code></pre>
<pre><code>## integer(0)</code></pre>
<p>According to the Hampel filter, there is no potential outlier for the <code>hwy</code> variable.</p>
</div>
<div id="statistical-tests" class="section level1">
<h1>Statistical tests</h1>
<p>In this section, we present 3 more formal techniques to detect outliers:</p>
<ol style="list-style-type: decimal">
<li>Grubbs’s test</li>
<li>Dixon’s test</li>
<li>Rosner’s test</li>
</ol>
<p>These 3 statistical tests are part of more formal techniques of outliers detection as they all involve the computation of a test statistic that is compared to tabulated critical values (that are based on the sample size and the desired confidence level).</p>
<p>Note that the 3 tests are appropriate only when the data (without any outliers) are <strong>approximately normally distributed</strong>. The normality assumption must thus be verified before applying these tests for outliers (see how to <a href="/blog/do-my-data-follow-a-normal-distribution-a-note-on-the-most-widely-used-distribution-and-how-to-test-for-normality-in-r/">test the normality assumption in R</a>).</p>
<div id="grubbss-test" class="section level2">
<h2>Grubbs’s test</h2>
<p>The Grubbs test allows to detect whether the highest or lowest value in a dataset is an outlier.</p>
<p>The Grubbs test detects one outlier at a time (highest or lowest value), so the null and alternative hypotheses are as follows:</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: The <em>highest</em> value is <strong>not</strong> an outlier</li>
<li><span class="math inline">\(H_1\)</span>: The <em>highest</em> value is an outlier</li>
</ul>
<p>if we want to test the highest value, or:</p>
<ul>
<li><span class="math inline">\(H_0\)</span>: The <em>lowest</em> value is <strong>not</strong> an outlier</li>
<li><span class="math inline">\(H_1\)</span>: The <em>lowest</em> value is an outlier</li>
</ul>
<p>if we want to test the lowest value.</p>
<p>As for any statistical test, if the <strong><a href="/blog/student-s-t-test-in-r-and-by-hand-how-to-compare-two-groups-under-different-scenarios/#a-note-on-p-value-and-significance-level-alpha"><em>p</em>-value</a> is less</strong> than the chosen <strong>significance threshold</strong> (generally <span class="math inline">\(\alpha = 0.05\)</span>) then the null hypothesis is rejected and we will conclude that the <strong>lowest/highest value is an outlier</strong>. On the contrary, if the <strong><em>p</em>-value is greater or equal</strong> than the significance level, the null hypothesis is not rejected, and we will conclude that, based on the data, we do not reject the hypothesis that the <strong>lowest/highest value is not an outlier</strong>.</p>
<p>Note that the Grubbs test is not appropriate for sample size of 6 or less (<span class="math inline">\(n \le 6\)</span>).</p>
<p>To perform the Grubbs test in R, we use the <code>grubbs.test()</code> function from the <code>{outliers}</code> package:</p>
<pre class="r"><code># install.packages(&quot;outliers&quot;)
library(outliers)
test &lt;- grubbs.test(dat$hwy)
test</code></pre>
<pre><code>## 
##  Grubbs test for one outlier
## 
## data:  dat$hwy
## G = 3.45274, U = 0.94862, p-value = 0.05555
## alternative hypothesis: highest value 44 is an outlier</code></pre>
<p>The <em>p</em>-value is 0.056. At the 5% significance level, we do not reject the hypothesis that the <em>highest</em> value 44 is <strong>not</strong> an outlier.</p>
<p>By default, the test is performed on the highest value (as shown in the R output: <code>alternative hypothesis: highest value 44 is an outlier</code>). If you want to do the test for the lowest value, simply add the argument <code>opposite = TRUE</code> in the <code>grubbs.test()</code> function:</p>
<pre class="r"><code>test &lt;- grubbs.test(dat$hwy, opposite = TRUE)
test</code></pre>
<pre><code>## 
##  Grubbs test for one outlier
## 
## data:  dat$hwy
## G = 1.92122, U = 0.98409, p-value = 1
## alternative hypothesis: lowest value 12 is an outlier</code></pre>
<p>The R output indicates that the test is now performed on the lowest value (see <code>alternative hypothesis: lowest value 12 is an outlier</code>).</p>
<p>The <em>p</em>-value is 1. At the 5% significance level, we do not reject the hypothesis that the <em>lowest</em> value 12 is <strong>not</strong> an outlier.</p>
<p>For the sake of illustration, we will now replace an observation with a more extreme value and perform the Grubbs test on this new dataset. Let’s replace the <span class="math inline">\(34^{th}\)</span> row with a value of 212:</p>
<pre class="r"><code>dat[34, &quot;hwy&quot;] &lt;- 212</code></pre>
<p>And we now apply the Grubbs test to test whether the highest value is an outlier:</p>
<pre class="r"><code>test &lt;- grubbs.test(dat$hwy)
test</code></pre>
<pre><code>## 
##  Grubbs test for one outlier
## 
## data:  dat$hwy
## G = 13.72240, U = 0.18836, p-value &lt; 2.2e-16
## alternative hypothesis: highest value 212 is an outlier</code></pre>
<p>The <em>p</em>-value is &lt; 0.001. At the 5% significance level, we conclude that the <em>highest</em> value 212 is an outlier.</p>
</div>
<div id="dixons-test" class="section level2">
<h2>Dixon’s test</h2>
<p>Similar to the Grubbs test, Dixon test is used to test whether a single low or high value is an outlier. So if more than one outliers is suspected, the test has to be performed on these suspected outliers individually.</p>
<p>Note that Dixon test is most useful for small sample size (usually <span class="math inline">\(n \le 25\)</span>).</p>
<p>To perform the Dixon’s test in R, we use the <code>dixon.test()</code> function from the <code>{outliers}</code> package. However, we <a href="/blog/data-manipulation-in-r/#subset-a-dataset">restrict our dataset</a> to the 20 first observations as the Dixon test can only be done on small sample size (R will throw an error and accepts only dataset of 3 to 30 observations):</p>
<pre class="r"><code>subdat &lt;- dat[1:20, ]
test &lt;- dixon.test(subdat$hwy)
test</code></pre>
<pre><code>## 
##  Dixon test for outliers
## 
## data:  subdat$hwy
## Q = 0.57143, p-value = 0.006508
## alternative hypothesis: lowest value 15 is an outlier</code></pre>
<p>The results show that the lowest value 15 is an outlier (<em>p</em>-value = 0.007).</p>
<p>To test for the highest value, simply add the <code>opposite = TRUE</code> argument to the <code>dixon.test()</code> function:</p>
<pre class="r"><code>test &lt;- dixon.test(subdat$hwy,
  opposite = TRUE
)
test</code></pre>
<pre><code>## 
##  Dixon test for outliers
## 
## data:  subdat$hwy
## Q = 0.25, p-value = 0.8582
## alternative hypothesis: highest value 31 is an outlier</code></pre>
<p>The results show that the highest value 31 is <strong>not</strong> an outlier (<em>p</em>-value = 0.858).</p>
<p>It is a good practice to always check the results of the statistical test for outliers against the boxplot to make sure we tested <strong>all</strong> potential outliers:</p>
<pre class="r"><code>out &lt;- boxplot.stats(subdat$hwy)$out
boxplot(subdat$hwy,
  ylab = &quot;hwy&quot;
)
mtext(paste(&quot;Outliers: &quot;, paste(out, collapse = &quot;, &quot;)))</code></pre>
<p><img src="/blog/2020-08-11-outliers-detection-in-r_files/figure-html/unnamed-chunk-24-1.png" width="100%" style="display: block; margin: auto;" /></p>
<p>From the boxplot, we see that we could also apply the Dixon test on the value 20 in addition to the value 15 done previously. This can be done by finding the row number of the minimum value, excluding this row number from the dataset and then finally apply the Dixon test on this new dataset:</p>
<pre class="r"><code># find and exclude lowest value
remove_ind &lt;- which.min(subdat$hwy)
subsubdat &lt;- subdat[-remove_ind, ]

# Dixon test on dataset without the minimum
test &lt;- dixon.test(subsubdat$hwy)
test</code></pre>
<pre><code>## 
##  Dixon test for outliers
## 
## data:  subsubdat$hwy
## Q = 0.44444, p-value = 0.1297
## alternative hypothesis: lowest value 20 is an outlier</code></pre>
<p>The results show that the second lowest value 20 is <strong>not</strong> an outlier (<em>p</em>-value = 0.13).</p>
</div>
<div id="rosners-test" class="section level2">
<h2>Rosner’s test</h2>
<p>Rosner’s test for outliers has the advantages that:</p>
<ol style="list-style-type: decimal">
<li>it is used to <strong>detect several outliers at once</strong> (unlike Grubbs and Dixon test which must be performed iteratively to screen for multiple outliers), and</li>
<li>it is designed to avoid the problem of masking, where an outlier that is close in value to another outlier can go undetected.</li>
</ol>
<p>Unlike Dixon test, note that Rosner test is most appropriate when the sample size is large (<span class="math inline">\(n \ge 20\)</span>). We therefore use again the initial dataset <code>dat</code>, which includes 234 observations.</p>
<p>To perform the Rosner test we use the <code>rosnerTest()</code> function from the <code>{EnvStats}</code> package. This function requires at least 2 arguments: the data and the number of suspected outliers <code>k</code> (with <code>k = 3</code> as the default number of suspected outliers).</p>
<p>For this example, we set the number of suspected outliers to be equal to 3, as suggested by the number of potential outliers outlined in the boxplot at the beginning of the article.<a href="#fn2" class="footnote-ref" id="fnref2"><sup>2</sup></a></p>
<pre class="r"><code>library(EnvStats)
test &lt;- rosnerTest(dat$hwy,
  k = 3
)
test</code></pre>
<pre><code>## $distribution
## [1] &quot;Normal&quot;
## 
## $statistic
##       R.1       R.2       R.3 
## 13.722399  3.459098  3.559936 
## 
## $sample.size
## [1] 234
## 
## $parameters
## k 
## 3 
## 
## $alpha
## [1] 0.05
## 
## $crit.value
## lambda.1 lambda.2 lambda.3 
## 3.652091 3.650836 3.649575 
## 
## $n.outliers
## [1] 1
## 
## $alternative
## [1] &quot;Up to 3 observations are not\n                                 from the same Distribution.&quot;
## 
## $method
## [1] &quot;Rosner&#39;s Test for Outliers&quot;
## 
## $data
##   [1]  29  29  31  30  26  26  27  26  25  28  27  25  25  25  25  24  25  23
##  [19]  20  15  20  17  17  26  23  26  25  24  19  14  15  17  27 212  26  29
##  [37]  26  24  24  22  22  24  24  17  22  21  23  23  19  18  17  17  19  19
##  [55]  12  17  15  17  17  12  17  16  18  15  16  12  17  17  16  12  15  16
##  [73]  17  15  17  17  18  17  19  17  19  19  17  17  17  16  16  17  15  17
##  [91]  26  25  26  24  21  22  23  22  20  33  32  32  29  32  34  36  36  29
## [109]  26  27  30  31  26  26  28  26  29  28  27  24  24  24  22  19  20  17
## [127]  12  19  18  14  15  18  18  15  17  16  18  17  19  19  17  29  27  31
## [145]  32  27  26  26  25  25  17  17  20  18  26  26  27  28  25  25  24  27
## [163]  25  26  23  26  26  26  26  25  27  25  27  20  20  19  17  20  17  29
## [181]  27  31  31  26  26  28  27  29  31  31  26  26  27  30  33  35  37  35
## [199]  15  18  20  20  22  17  19  18  20  29  26  29  29  24  44  29  26  29
## [217]  29  29  29  23  24  44  41  29  26  28  29  29  29  28  29  26  26  26
## 
## $data.name
## [1] &quot;dat$hwy&quot;
## 
## $bad.obs
## [1] 0
## 
## $all.stats
##   i   Mean.i      SD.i Value Obs.Num     R.i+1 lambda.i+1 Outlier
## 1 0 24.21795 13.684345   212      34 13.722399   3.652091    TRUE
## 2 1 23.41202  5.951835    44     213  3.459098   3.650836   FALSE
## 3 2 23.32328  5.808172    44     222  3.559936   3.649575   FALSE
## 
## attr(,&quot;class&quot;)
## [1] &quot;gofOutlier&quot;</code></pre>
<p>The interesting results are provided in the <code>$all.stats</code> table:</p>
<pre class="r"><code>test$all.stats</code></pre>
<pre><code>##   i   Mean.i      SD.i Value Obs.Num     R.i+1 lambda.i+1 Outlier
## 1 0 24.21795 13.684345   212      34 13.722399   3.652091    TRUE
## 2 1 23.41202  5.951835    44     213  3.459098   3.650836   FALSE
## 3 2 23.32328  5.808172    44     222  3.559936   3.649575   FALSE</code></pre>
<p>Based on the Rosner test, we see that there is only one outlier (see the <code>Outlier</code> column), and that it is the observation 34 (see <code>Obs.Num</code>) with a value of 212 (see <code>Value</code>).</p>
</div>
</div>
<div id="additional-remarks" class="section level1">
<h1>Additional remarks</h1>
<p>You will find many other methods to detect outliers:</p>
<ol style="list-style-type: decimal">
<li>in the <code>{outliers}</code> packages,</li>
<li>via the <code>lofactor()</code> function from the <code>{DMwR}</code> package: Local Outlier Factor (LOF) is an algorithm used to identify outliers by comparing the local density of a point with that of its neighbors,</li>
<li>the <code>outlierTest()</code> from the <code>{car}</code> package gives the most extreme observation based on the given model and allows to test whether it is an outlier,</li>
<li>in the <code>{OutlierDetection}</code> package, and</li>
<li>with the <code>aq.plot()</code> function from the <code>{mvoutlier}</code> package (Thanks KTR for the suggestion.):</li>
</ol>
<pre class="r"><code>library(mvoutlier)

Y &lt;- as.matrix(ggplot2::mpg[, c(&quot;cyl&quot;, &quot;hwy&quot;)])
res &lt;- aq.plot(Y)</code></pre>
<p><img src="/blog/2020-08-11-outliers-detection-in-r_files/figure-html/unnamed-chunk-28-1.png" width="100%" style="display: block; margin: auto;" /></p>
<p>Note also that some transformations may “naturally” eliminate outliers. The natural log or square root of a value reduces the variation caused by extreme values, so in some cases applying these transformations will eliminate the outliers.</p>
<p>Thanks for reading. I hope this article helped you to detect outliers in R via several <a href="/blog/descriptive-statistics-in-r/">descriptive statistics</a> (including minimum, maximum, histogram, boxplot and percentiles) or thanks to more formal techniques of outliers detection (including Hampel filter, Grubbs, Dixon and Rosner test). It is now your turn to verify them, and if they are correct, decide how to treat them (i.e., keeping, removing or imputing them) before conducting your analyses.</p>
<p>As always, if you have a question or a suggestion related to the topic covered in this article, please add it as a comment so other readers can benefit from the discussion.</p>
</div>
<div id="reference" class="section level1 unnumbered">
<h1>Reference</h1>
<div id="refs" class="references">
<div id="ref-enderlein1987hawkins">
<p>Enderlein, G. 1987. “Hawkins, Dm: Identification of Outliers. Chapman and Hall, London–New York 1980, 188 S.,£ 14, 50.” <em>Biometrical Journal</em> 29 (2): 198–98.</p>
</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>The default is 3 (according to Pearson’s rule), but another value is also possible.<a href="#fnref1" class="footnote-back">↩︎</a></p></li>
<li id="fn2"><p>In order to avoid flawed conclusions, it is important to pre-screen the data (graphically with a boxplot for example) to make the selection of the number of potential outliers as accurate as possible prior to running Rosner’s test.<a href="#fnref2" class="footnote-back">↩︎</a></p></li>
</ol>
</div>



                    </div>

<br>                    

      <div class="related">

<h3>Related articles</h3>
<ul>
	
	<li><a href="/blog/anova-in-r/">ANOVA in R</a></li>
	
	<li><a href="/blog/wilcoxon-test-in-r-how-to-compare-2-groups-under-the-non-normality-assumption/">Wilcoxon test in R: how to compare 2 groups under the non-normality assumption</a></li>
	
	<li><a href="/blog/correlation-coefficient-and-correlation-test-in-r/">Correlation coefficient and correlation test in R</a></li>
	
	<li><a href="/blog/one-proportion-and-goodness-of-fit-test-in-r-and-by-hand/">One-proportion and goodness of fit test (in R and by hand)</a></li>
	
	<li><a href="/blog/how-to-do-a-t-test-or-anova-for-many-variables-at-once-in-r-and-communicate-the-results-in-a-better-way/">How to do a t-test or ANOVA for more than one variable at once in R</a></li>
	
</ul>
</div>
      
      
      <br>
      <h3>Liked this post?</h3> <b>Get updates</b> every time a new article is published.
      <br>
      <small><i>No spam and unsubscribe anytime.</i></small>
      

<link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{background:#fff; clear:left; font:14px Helvetica,Arial,sans-serif; width: 300px;}
	 
</style>
<div id="mc_embed_signup">
<form action="https://statsandr.us4.list-manage.com/subscribe/post?u=dbadb70b4f121c714d12c9fc5&amp;id=f8729988c2" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
    <div id="mc_embed_signup_scroll">
	
<div class="mc-field-group">
	<input type="email" placeholder="Email address" value="" name="EMAIL" class="required email" id="mce-EMAIL">
</div>
<div class="mc-field-group">
	<input type="text" placeholder="First name" value="" name="FNAME" class="required" id="mce-FNAME">
</div>
	<div id="mce-responses" class="clear">
		<div class="response" id="mce-error-response" style="display:none"></div>
		<div class="response" id="mce-success-response" style="display:none"></div>
	</div>    
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_dbadb70b4f121c714d12c9fc5_f8729988c2" tabindex="-1" value="">
    </div>
    
    <div class="clear"><input type="submit" value="Receive new posts by email" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
    </div>
</form>
</div>


<br>

<ul class="share-buttons">
  Share on:
  <li><a href="https://www.facebook.com/sharer/sharer.php?u=https%3A%2F%2Fstatsandr.com%2F&quote=" title="Share on Facebook" target="_blank" onclick="window.open('https://www.facebook.com/sharer/sharer.php?u=' + encodeURIComponent(document.URL) + '&quote=' + encodeURIComponent(document.URL)); return false;"><img alt="Share on Facebook" src="img/facebook-f-brands.svg" width="28" height="28" /></a></li>
  <li><a href="https://twitter.com/intent/tweet?source=https%3A%2F%2Fstatsandr.com%2F&text=:%20https%3A%2F%2Fstatsandr.com%2F&via=statsandr" target="_blank" title="Tweet" onclick="window.open('https://twitter.com/intent/tweet?text=' + encodeURIComponent(document.title) + ':%20'  + encodeURIComponent(document.URL)); return false;"><img alt="Tweet" src="img/twitter.svg" width="28" height="28" /></a></li>
  <li><a href="http://www.linkedin.com/shareArticle?mini=true&url=https%3A%2F%2Fstatsandr.com%2F&title=&summary=&source=https%3A%2F%2Fstatsandr.com%2F" target="_blank" title="Share on LinkedIn" onclick="window.open('http://www.linkedin.com/shareArticle?mini=true&url=' + encodeURIComponent(document.URL) + '&title=' +  encodeURIComponent(document.title)); return false;"><img alt="Share on LinkedIn" src="img/linkedin-in-brands.svg" width="28" height="28" /></a></li>
  <li><a href="mailto:?subject=&body=:%20https%3A%2F%2Fstatsandr.com%2F" target="_blank" title="Send email" onclick="window.open('mailto:?subject=' + encodeURIComponent(document.title) + '&body=' +  encodeURIComponent(document.URL)); return false;"><img alt="Send email" src="img/envelope-solid.svg" width="28" height="28" /></a></li>
</ul>

      
      <br>
      <p><a href="#top">&uarr; Back to top</a></p>
      <br>
      
<script src="https://utteranc.es/client.js"
        repo="AntoineSoetewey/statsandr"
        issue-term="pathname"
        label="comment"
        theme="github-light"
        crossorigin="anonymous"
        async>
</script>

                    
                        <div class="navigation">
                            <div class="row">
                                <div class="col-12 col-md-6">
                                    
                                        <div class="mx-0 mx-md-4 mt-4 text-left">
                                            <a href="/blog/wilcoxon-test-in-r-how-to-compare-2-groups-under-the-non-normality-assumption/">« Wilcoxon test in R: how to compare 2 groups under the non-normality assumption</a>
                                        </div>
                                    
                                </div>
                                <div class="col-12 col-md-6">
                                    
                                        <div class="mx-0 mx-md-4 mt-4 text-right">
                                            <a href="/blog/mortgage-calculator-r-shiny/">Mortgage calculator in R Shiny »</a>
                                        </div>
                                    
                                </div>
                            </div>
                        </div>
                    
                </div>
            </div>
        </div>
    </div>

    <section id="comments">
    <div class="py-3 content">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-sm-12 col-lg-8">
                    <div class="comments">
                        <script src="https://utteranc.es/client.js" repo=""
                            issue-term="pathname" label="comment" theme="github-light" crossorigin="anonymous" async>
                            </script>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
    <div class="my-4 footer">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-12 col-md-5">
                
                    <div class="mx-0 mx-md-4 text-left">
                        
                            <p>
                              <a href="/subscribe/">Newsletter</a>
                              <a href="/faq/">FAQ</a>
                              <a href="/contribute/">Contribute</a>
                              <a href="/support/">Support</a>
                              <a href="/sitemap/">Sitemap</a>
                            </p>
                            <p>
                              <a href="/">&copy; <script>document.write(new Date().getFullYear())</script> Antoine Soetewey</a><a href="/terms/">Terms</a>
                            </p>
                        
                    </div>
                
            </div>
            <div class="col-sm-12 col-md-5">
                <div class="mx-0 mx-md-4 text-right">
                  
                  
                    <a href="https://twitter.com/statsandr" target="_blank">
                        <img class="icon" src="/img/twitter.svg" alt="Twitter" title="Twitter"/>
                    </a>
                    
                    
                    
                        <a href="https://github.com/AntoineSoetewey" target="_blank">
                            <img class="icon" src="/img/github.svg" alt="GitHub" title="GitHub"/>
                        </a>
                    
                    
                    
                    <a href="https://antoinesoetewey.medium.com/" target="_blank">
                        <img class="icon" src="/img/medium-m-brands.svg" alt="Medium" title="Medium"/>
                    </a>
                    

                    

                    

                    

                    

                    

                    
                    
                    
                    <a href="/contact/">
                        <img class="icon" src="/img/envelope-solid.svg" alt="Contact" title="Contact"/>
                    </a>
                    

                    
                        <a href="/index.xml" class="mr-0">
                            <img class="icon" src="/img/rss.svg" alt="RSS" title="RSS"/>
                        </a>
                    

                    
                </div>
            </div>
        </div>
    </div>
</div>



    

    
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.14.2/highlight.min.js" integrity="sha256-sNPiigbfSkqUzMc5rgrdztLnneCMAp6W9wetJUZu9Zw=" crossorigin="anonymous"></script>
        
        <script>
            window.addEventListener('load', function() {
                hljs.initHighlighting();
            }, true);
        </script>
    

    

    
<script type="application/javascript">
var doNotTrack = false;
if (!doNotTrack) {
	window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
	ga('create', 'UA-86997981-2', 'auto');
	
	ga('send', 'pageview');
}
</script>
<script async src='https://www.google-analytics.com/analytics.js'></script>

    
        
<script src="/js/math-code.js"></script>
<script async src="//cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML"></script>


    
</body>

</html>